### ISSUE TITLE
Parametrized URLs

### ISSUE THREAD

**Issue by unitto1** [florimondmanca/ddtrace-asgi#23]
In case of usage URL template like a `users/{user_id}`.
Will middleware send the template (`users/{user_id}`) URL or the given URL (example: `users/2`)?

**Comment by florimondmanca** [comment]
Hi @unitto1!

The middleware always sends the requested URL, regardless of the framework used.

Relevant code is here:

https://github.com/florimondmanca/ddtrace-asgi/blob/fade79a9a54d3bad62061bf57a040a928bb81cf1/src/ddtrace_asgi/middleware.py#L70

(Where `url` refers `request.url`, so `str(url)` outputs the full, absolute requested URL, e.g. `http://localhost/users/2`.)

Would you expect the middleware to only send the URL *path*, e.g. `/users/2`.

**Comment by unitto1** [comment]
@florimondmanca Hey! Ty for so fast answer!

I expect the `http://localhost/users/{user_id}` instead of `http://localhost/users/2` =( but seems it requires the framework integration (ASGI standard does not provide path template =()

**Comment by florimondmanca** [comment]
Exactly, this use case seems to require integration at the framework level, since that information is not available at the ASGI level. Aso not sure whether e.g. Starlette gives you access to that template either.

That said, you should be able to use [manual instrumentation](http://pypi.datadoghq.com/trace/docs/basic_usage.html#manual-instrumentation) to add extra tags when a view gets executed. In particular, `tracer.current_span()` will return the [`Span`](http://pypi.datadoghq.com/trace/docs/advanced_usage.html#span) object that the middleware has set up for the current request.

So, at the cost of minimal duplication of URL templates, you could e.g. build a decorator to automatically add the URL template in a tag everytime a view is executed:

```python
import functools
from ddtrace import tracer

def trace_url_template(template: str):
    def decorate(view):

        @functools.wraps(view)
        async def wrapped(request):
            span = tracer.current_span()  # <-- This was setup by the middleware
            span.set_tag("url_template", value)
            return await view(request)

        return wrapped

    return decorate
    

@app.route("/users/{user_id:int}")
@trace_url_template("/users/{user_id}")
async def get_user(request):
    ...
```

**Comment by unitto1** [comment]
hm... interesting workaround... tnx!
