### ISSUE TITLE
ddtrace contribution 

### ISSUE THREAD

**Issue by andrei-shabanski** [florimondmanca/ddtrace-asgi#41]
Your package is amazing! I recently looked for something that's similar to this tool, and your middlerawe helped me out.

However, this's an unofficial integration and seems the project is in the alpha stage yet (according to README). So it might be quite risky to use in production.

Have you thought about moving the middleware to ddtrace repo? I think ddtrace team would be happy about any contribution. Also, their community may help to debug and improve the middleware.

**Comment by florimondmanca** [comment]
Hi!

Thanks the the kind words :)

You're right, since this is a community package for now you shouldn't expect the same support that you'd get from an official ddtrace integration. (Although this package follows SemVer so as long as you pin dependencies you'd be able to properly review changes before upgrading.)

I'm more than open to see this move to `dd-trace-py`. Actually @majorgreys and I discussed this some time ago, and I believe this is now in the Datadog APM team's backlog.

Moving this to core is actually not a trivial task, as there'd be some work to make this integration fit with the code practices of the `dd-trace-py` repo (eg Python 2.7 compatibility? tests rewrite? etc…). This is why I personally haven't got to open a PR myself there yet. (I use this package to monitor a Starlette site, so the current situation is enough for me.)

If you'd like to see official support for ASGI in Datadog APM, I'd suggest chiming in with the core maintainers over at [`dd-trace-py`](https://github.com/DataDog/dd-trace-py). :-)
