### ISSUE TITLE
Infer service value from DATADOG_SERVICE_NAME

### ISSUE THREAD

**Issue by jcwilson** [florimondmanca/ddtrace-asgi#43]
The underlying `ddtrace` library looks for the service name in the `DATADOG_SERVICE_NAME` environment variable. Is there any reason we couldn't do the same here? It's slightly cumbersome to have to explicitly provide it to the `TraceMiddleware` when it may not be necessary.

**Comment by florimondmanca** [comment]
Not really a reason no, I was not aware that this environment variable was available and used by default by ddtrace.

Also please note that given https://github.com/DataDog/dd-trace-py/pull/1567, I am planning to deprecate this package soon. I'd suggest looking at the PR to see if it follows the usage of DD_SERVICE_NAME you're expecting (I believe so, since I don't remember seeing a mention of `service` while reviewing the PR there).

**Comment by jcwilson** [comment]
ah, ok. No worries.

Congratulations on getting this integrated to the mainline package! Looking forward to it. Feel free to close this.
